name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
api-version: 1.19
version: ${project.version}
build: ${project.build.number}
authors: [${project.authors}]
load: startup
description: Is used in all of my plugins to re-use common functions
dependencies:
  - name: Vault
    required: false
  - name: ProtocolLib
    required: false
  - name: WorldEdit
    required: false
  - name: FastAsyncWorldEdit
    required: false
  - name: ViaVersion
    required: false
  - name: LuckPerms
    required: false
  - name: InteractiveBoard
    required: false
load-after:
  - name: Vault
  - name: ProtocolLib
dev-url: ${project.url}
preloader:
  hastebinServer: https://paste.traincarts.net
permissions:
  bkcommonlib.debug.variables:
    default: OP
    description: |
      Allows use of the /debugvar command.
      This command is only available when debugging variables are set.
      In normal production builds, this command and permission are unused.
