name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
api-version: 1.13
version: ${project.version}
build: ${project.build.number}
authors: [bergerkiller, lenis0012, timstans, bubba1234119, KamikazePlatypus, mg_1999, Friwi]
load: startup
description: Is used in all of my plugins to re-use common functions
softdepend: [Vault, ProtocolLib, ViaVersion, LuckPerms, WorldEdit]
dev-url: ${project.url}
preloader:
  hastebinServer: https://paste.traincarts.net
permissions:
  bkcommonlib.debug.variables:
    default: OP
    description: |
        Allows use of the /debugvar command.
        This command is only available when debugging variables are set.
        In normal production builds, this command and permission are unused.
