name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
version: 1.49
authors: [bergerkiller, lenis0012]
load: startup
description: Is used in all of my plugins to re-use common functions
softdepend: [Vault, ProtocolLib]
dev-url: http://dev.bukkit.org/server-mods/bkcommonlib/