name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
version: 1.29
author: bergerkiller
load: startup
description: Is used in all of my plugins to re-use common functions
dev-url: http://dev.bukkit.org/server-mods/bkcommonlib/